server:
  port: 8082
spring:
  application:
    name: github-action-practice
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_IP}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PW}


