version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/deploy/github-action-practice
    overwrite: yes

permissions:
  - object: /home/ubuntu/deploy/github-action-practice
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
