server:
  port: 8081
spring:
  application:
    name: github-action-practice
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:gitdb
    driver-class-name: org.h2.Driver
    username: gitdb
    password: gitdb123


