name: Build when a push or pull_request to main is made

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types:
      -closed

jobs:
  build:
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    
    permissions:
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.6
    - name: Gradle Build Action with Gradle Wrapper
      run: ./gradlew build
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.7.0
      if: ${{ always() }}
      with:
        files: build/test-results/**/*.xml
